In [1]:
#Importing Libraries
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import pandas as pd


header = {
    "User_Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/84.0.4147.89 Safari/537.36"
}

Get_Details = []
for x in range(1,10):
    
    link = f'https://www.naukri.com/data-science-jobs-in-hyderabad-{x}?k=data%20science&l=hyderabad'
    driver = webdriver.Chrome("D:\\ChromeD\\chromedriver.exe")
    driver.get(link)
    time.sleep(10)
    soup = BeautifulSoup(driver.page_source,"html5lib")
    #getting the list of contents
    driver.close()
    
    get_list = soup.find(class_ = "list")
    get_cont = get_list.find_all("article", class_ = "jobTuple bgWhite br4 mb-8")
    
    for i in get_cont:
        
        #getting the job position
        position = i.find(class_ = "title fw500 ellipsis").get_text()     
        
        #getting the company name
        company = i.find(class_ = "subTitle ellipsis fleft").get_text()
        
        #getting the company rating
        try:
            rating = i.find(class_ = "starRating fleft dot").get_text()
        except:
            rating = "Nan"
        
        #getting the experience needed
        try:
            experience = i.find(class_ = "subTitle ellipsis fleft").get_text()
        except:
            experience = "Nan"
        
        #getting the salary details
        try:
            salary = i.find(class_ = "fleft grey-text br2 placeHolderLi salary").get_text()
        except:
            salary = "Nan"
        
        try:
            location = i.find(class_ = "fleft grey-text br2 placeHolderLi location").get_text()
            
        except:
            location = "Nan"
        
        #getting skills details
        try:
            skills = i.find(class_ = "tags has-description").get_text()
        except:
            skills = "Nan"
        
        
        #getting the post link
        try:
            link = i.find(class_ = "title fw500 ellipsis").get("href")
        except:
            link = "NaN"
        
        Details = {"Company": company,
                    "Rating" : rating,
                    "Position" : position,
                    "Experience" : experience,
                    "Salary" : salary,
                    "Location" : location,
                    "Skills" : skills,
                    "Link" : link
            }

        Get_Details.append(Details)

In [2]:
df = pd.DataFrame(Get_Details)
df.head()

,Company,Rating,Position,Experience,Salary,Location,Skills,Link
0,Uber,3.9,Risk Strategy Analyst - Data science,Uber,Not disclosed,Hyderabad/Secunderabad,Product managementComputer scienceStatistical ...,https://www.naukri.com/job-listings-risk-strat...
1,Conduent,3.5,"Senior Manager , Data Science",Conduent,Not disclosed,"Hyderabad/Secunderabad, Bangalore/Bengaluru",IT SkillsPythonData ScienceMachine LearningBig...,https://www.naukri.com/job-listings-senior-man...
2,Reliance Jio Infocomm Ltd.,4.0,Manager Data Science,Reliance Jio Infocomm Ltd.,Not disclosed,Hyderabad/Secunderabad,Report generationData managementMachine learni...,https://www.naukri.com/job-listings-manager-da...
3,Remah IT,Nan,Business Consultant - Data Science,Remah IT,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Banga...",AWSAzureGCPData ScienceData ArchitectGoogle Cl...,https://www.naukri.com/job-listings-business-c...
4,CarbyneTech India,2.7,Splunk Developer - SQL / Data Science,CarbyneTech India,Not disclosed,Hyderabad/Secunderabad,SQLSplunk Developer Java Splunk DashboardsAgi...,https://www.naukri.com/job-listings-splunk-dev...

In [3]:
df.to_csv("Hyderabad DS Job DataSets.csv",index=False)

In [4]:
df.shape

(180, 8)